<JournalEntryCard>:
    focus_behavior: True
    md_bg_color: Theme.get_primary_colour()
    focus_color: Theme.get_focus_colour()
    unfocus_color: Theme.get_primary_colour()
    style: "filled"

    MDLabel:
        text: root.title
        color: "black"
        bold: True
        size_hint: None, None
        size: root.width, root.height-35
        pos_hint: {"center_y": .5}
        halign: "center"
        font_name: Theme.get_card_title_font()